### ISSUE TITLE
Few Corrections and Tips

### ISSUE THREAD

**Issue by fizerkhan** [plantpark/scaleable-crawler-with-docker-cluster#1]
Thank you so much for the open sourcing the code and detailed article. 

I found few tips to be followed to make it work:

### RabbitMQ Host

In your `test_celery/celery.py` you have to set broker url as `broker='amqp://admin:mypass@rabbit:5672'`

### Running a tasks

You have to execute a `run_tasks` inside a worker container instead of host machine.

      sudo docker exec -i -t scaleablecrawlerwithdockercluster_worker_1 /bin/bash
      python -m test_celery.run_tasks

Where `scaleablecrawlerwithdockercluster_worker_1` is a container name. Make sure you replace it with your worker container name or id.

### Access MongoDB from the host machine to see the results.

    mongo --host 172.18.0.1 --port 27018

#### Question about docker-engine:

In the [medium article](https://medium.com/@tonywangcn/how-to-build-docker-cluster-with-celery-and-rabbitmq-in-10-minutes-13fc74d21730), you said about installation of `docker-engine`.  I think. we only need installation `docker ` and `docker-compose`.  I installed both docker and docker-compose using following steps

```
1. Install Docker

Refer: https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/


    sudo apt-get remove docker docker-engine docker.io

    sudo apt-get update
    sudo apt-get install \
        apt-transport-https \
        ca-certificates \
        curl \
        software-properties-common


    sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    sudo apt-key fingerprint 0EBFCD88

    sudo add-apt-repository \
       "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
       $(lsb_release -cs) \
       stable"

    sudo apt-get update
    sudo apt-get install docker-ce
    sudo docker --version

2. Install Docker-compose

    sudo curl -L https://github.com/docker/compose/releases/download/1.18.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
    sudo chmod +x /usr/local/bin/docker-compose
    sudo docker-compose --version
```
Could you please update the same on the article?

**Comment by tonywangcn** [comment]
update , Thanks!
